SHOW VARIABLES LIKE 'event_scheduler';
SET GLOBAL event_scheduler=ON;


CREATE EVENT autoDeleteSessions
ON SCHEDULE EVERY 1 DAY
STARTS CURRENT_TIMESTAMP + INTERVAL 1 DAY
DO
  DELETE FROM TABLE_EXAMPLE.`session` WHERE expires_in  < CURDATE() - INTERVAL 2 DAY;

SHOW EVENTS;

-- Execute Now
ALTER EVENT autoDeleteSessions
ON SCHEDULE AT '2023-07-11T05:24:00';